// src/seed/programs.js
const programs = [
  {
    id: 1,
    name: "CapCut",
    categoryLabel: "AI Video",
    epu: "$49.5",
    commission: "30% - 45%",
    traffic: "41.6M /mo",
    recurring: "Lifetime",
    pricing: "$9.99",
    country: "China (CN)",
    link: "https://www.capcut.com"
  },
  {
    id: 2,
    name: "ElevenLabs",
    categoryLabel: "AI Audio",
    epu: "$136.18",
    commission: "22%",
    traffic: "23.6M /mo",
    recurring: "12 months",
    pricing: "$4.17 - $99",
    country: "United States (US)",
    link: "https://elevenlabs.io"
  },
  {
    id: 3,
    name: "Gamma",
    categoryLabel: "AI Presentation",
    epu: "$50.4",
    commission: "30%",
    traffic: "21.7M /mo",
    recurring: "12 months",
    pricing: "$8 - $20",
    country: "United States (US)",
    link: "https://gamma.app"
  },
  {
    id: 4,
    name: "Lovable",
    categoryLabel: "AI No-Code/Low-Code",
    epu: "$16.5",
    commission: "10%",
    traffic: "21.1M /mo",
    recurring: "6 months",
    pricing: "$25 - $30",
    country: "Sweden (SE)",
    link: "https://lovable.app"
  },
  {
    id: 5,
    name: "Fotor",
    categoryLabel: "AI Design",
    epu: "$42.12",
    commission: "25% - 35%",
    traffic: "16.2M /mo",
    recurring: "12 months",
    pricing: "$3.33 - $19.99",
    country: "China (CN)",
    link: "https://fotor.com"
  },
  {
    id: 6,
    name: "n8n",
    categoryLabel: "AI Workflow",
    epu: "€144",
    commission: "30%",
    traffic: "12M /mo",
    recurring: "12 months",
    pricing: "$20 - $60",
    country: "Germany (DE)",
    link: "https://n8n.io"
  },
  {
    id: 7,
    name: "VEED",
    categoryLabel: "AI Video",
    epu: "$104.4",
    commission: "30%",
    traffic: "11.6M /mo",
    recurring: "12 months",
    pricing: "$9 - $49",
    country: "United Kingdom (GB)",
    link: "https://veed.io"
  },
  {
    id: 8,
    name: "Monica",
    categoryLabel: "AI All In One",
    epu: "$43.5",
    commission: "25%",
    traffic: "9.8M /mo",
    recurring: "12 months",
    pricing: "$4.1 - $24.9",
    country: "China (CN)",
    link: "https://monica.im"
  },
  {
    id: 9,
    name: "GoHighLevel",
    categoryLabel: "AI Tools",
    epu: "$945.6",
    commission: "40%",
    traffic: "8.5M /mo",
    recurring: "12 months",
    pricing: "$97 - $297",
    country: "United States (US)",
    link: "https://www.gohighlevel.com"
  },
  {
    id: 10,
    name: "OpenArt",
    categoryLabel: "AI Design",
    epu: "$189",
    commission: "20% - 30%",
    traffic: "8.2M /mo",
    recurring: "12 months",
    pricing: "$7 - $56",
    country: "United States (US)",
    link: "https://openart.ai"
  },
  {
    id: 11,
    name: "GetResponse",
    categoryLabel: "AI Email",
    epu: "$1,288.5",
    commission: "40% - 60%",
    traffic: "7.7M /mo",
    recurring: "12 months",
    pricing: "$15.5 - $414",
    country: "Poland (PL)",
    link: "https://getresponse.com"
  },
  {
    id: 12,
    name: "Invideo AI",
    categoryLabel: "AI Video",
    epu: "$27.75",
    commission: "25% - 50%",
    traffic: "7.4M /mo",
    recurring: "One time",
    pricing: "$28 - $120",
    country: "United States (US)",
    link: "https://invideo.io"
  },
  {
    id: 13,
    name: "HeyGen",
    categoryLabel: "AI Video",
    epu: "$75.6",
    commission: "20%",
    traffic: "7M /mo",
    recurring: "12 months",
    pricing: "$24 - $39",
    country: "United States (US)",
    link: "https://heygen.com"
  },
  {
    id: 14,
    name: "BASE44",
    categoryLabel: "AI No-Code/Low-Code",
    epu: "$132",
    commission: "20%",
    traffic: "6.3M /mo",
    recurring: "6 months",
    pricing: "$20 - $200",
    country: "United States (US)",
    link: "#"
  },
  {
    id: 15,
    name: "Make",
    categoryLabel: "AI Workflow",
    epu: "$103.68",
    commission: "20%",
    traffic: "5.7M /mo",
    recurring: "24 months",
    pricing: "$9 - $34.12",
    country: "Czech Republic (CZ)",
    link: "https://www.make.com"
  },
  {
    id: 16,
    name: "Scispace",
    categoryLabel: "AI Detector",
    epu: "$9.18",
    commission: "18%",
    traffic: "5.2M /mo",
    recurring: "One time",
    pricing: "$12 - $90",
    country: "India (IN)",
    link: "https://typeset.io"
  },
  {
    id: 17,
    name: "Kapwing",
    categoryLabel: "AI Video",
    epu: "$144",
    commission: "25% - 35%",
    traffic: "5.2M /mo",
    recurring: "12 months",
    pricing: "$16 - $64",
    country: "United States (US)",
    link: "https://kapwing.com"
  },
  {
    id: 18,
    name: "Sider",
    categoryLabel: "AI All In One",
    epu: "$49.68",
    commission: "15%",
    traffic: "5.2M /mo",
    recurring: "Lifetime",
    pricing: "$6.7 - $30",
    country: "United States (US)",
    link: "https://sider.ai"
  },
  {
    id: 19,
    name: "vidIQ",
    categoryLabel: "AI Video",
    epu: "$100.08",
    commission: "15% - 25%",
    traffic: "5.1M /mo",
    recurring: "Lifetime",
    pricing: "$16.58 - $39",
    country: "United States (US)",
    link: "https://vidiq.com"
  },
  {
    id: 20,
    name: "Clipto.AI",
    categoryLabel: "AI Transcription",
    epu: "$224.91",
    commission: "50%",
    traffic: "4.8M /mo",
    recurring: "Lifetime",
    pricing: "$24.99",
    country: "United States (US)",
    link: "#"
  },
  {
    id: 21,
    name: "Vidnoz",
    categoryLabel: "AI Video",
    epu: "$98.16",
    commission: "50% - 70%",
    traffic: "4.6M /mo",
    recurring: "4 months",
    pricing: "$6.74 - $74.99",
    country: "United States (US)",
    link: "https://vidnoz.com"
  },
  {
    id: 22,
    name: "Fireflies",
    categoryLabel: "AI Notetaker",
    epu: "$46.8",
    commission: "10% - 30%",
    traffic: "3.5M /mo",
    recurring: "12 months",
    pricing: "$10 - $29",
    country: "United States (US)",
    link: "https://fireflies.ai"
  },
  {
    id: 23,
    name: "PromeAI",
    categoryLabel: "AI Design",
    epu: "$57",
    commission: "10%",
    traffic: "3.4M /mo",
    recurring: "12 months",
    pricing: "$16 - $79",
    country: "China (CN)",
    link: "https://promeai.com"
  },
  {
    id: 24,
    name: "Descript",
    categoryLabel: "AI Video",
    epu: "$55.8",
    commission: "15%",
    traffic: "3.2M /mo",
    recurring: "12 months",
    pricing: "$15 - $50",
    country: "United States (US)",
    link: "https://descript.com"
  },
  {
    id: 25,
    name: "Kittl",
    categoryLabel: "AI Design",
    epu: "$120",
    commission: "20%",
    traffic: "3M /mo",
    recurring: "12 months",
    pricing: "$10 - $90",
    country: "Germany (DE)",
    link: "https://kittl.com"
  },
  {
    id: 26,
    name: "Deevid AI",
    categoryLabel: "AI Video",
    epu: "$25.35",
    commission: "30%",
    traffic: "2.9M /mo",
    recurring: "One time",
    pricing: "$10 - $159",
    country: "United States (US)",
    link: "#"
  },
  {
    id: 27,
    name: "Lalal.ai",
    categoryLabel: "AI Audio",
    epu: "$13.5",
    commission: "30%",
    traffic: "2.8M /mo",
    recurring: "Lifetime",
    pricing: "$20 - $70",
    country: "Russia (RU)",
    link: "https://lalal.ai"
  },
  {
    id: 28,
    name: "FlexClip",
    categoryLabel: "AI Video",
    epu: "$28.66",
    commission: "35%",
    traffic: "2.6M /mo",
    recurring: "One time",
    pricing: "$19.99 - $29.99",
    country: "China (CN)",
    link: "https://flexclip.com"
  },
  {
    id: 29,
    name: "Meshy AI",
    categoryLabel: "AI 3D Model",
    epu: "$91.2",
    commission: "20%",
    traffic: "2.5M /mo",
    recurring: "12 months",
    pricing: "$16 - $60",
    country: "United States (US)",
    link: "https://meshy.ai"
  },
  {
    id: 30,
    name: "Looka",
    categoryLabel: "AI Design",
    epu: "$33.75",
    commission: "25% - 35%",
    traffic: "2.4M /mo",
    recurring: "Lifetime",
    pricing: "$96 - $129",
    country: "Canada (CA)",
    link: "https://looka.com"
  },
  {
    id: 31,
    name: "HIX.AI",
    categoryLabel: "AI Writing",
    epu: "$242.46",
    commission: "30%",
    traffic: "2.2M /mo",
    recurring: "Lifetime",
    pricing: "$4.9 - $84.98",
    country: "Singapore (SG)",
    link: "https://hix.ai"
  },
  {
    id: 32,
    name: "VideoProc",
    categoryLabel: "AI Video",
    epu: "$571.68",
    commission: "30% - 50%",
    traffic: "2.2M /mo",
    recurring: "Lifetime",
    pricing: "$38.9 - $119.9",
    country: "United States (US)",
    link: "https://videoproc.com"
  },
  {
    id: 33,
    name: "Synthesia",
    categoryLabel: "AI Video",
    epu: "$160.5",
    commission: "25%",
    traffic: "2.1M /mo",
    recurring: "12 months",
    pricing: "$18 - $89",
    country: "United Kingdom (GB)",
    link: "https://synthesia.io"
  },
  {
    id: 34,
    name: "Apify",
    categoryLabel: "AI Web Scraper",
    epu: "$631.8",
    commission: "30%",
    traffic: "2.1M /mo",
    recurring: "Lifetime",
    pricing: "$35 - $199",
    country: "United States (US)",
    link: "https://apify.com"
  },
  {
    id: 35,
    name: "Merlin AI",
    categoryLabel: "AI All In One",
    epu: "$118.8",
    commission: "30%",
    traffic: "2.1M /mo",
    recurring: "Lifetime",
    pricing: "$15 - $29",
    country: "United States (US)",
    link: "https://merlin.fo"
  },
  {
    id: 36,
    name: "LiveChat",
    categoryLabel: "AI Chatbot",
    epu: "$149.31",
    commission: "20% - 22%",
    traffic: "2M /mo",
    recurring: "Lifetime",
    pricing: "$20 - $59",
    country: "United States (US)",
    link: "https://livechat.com"
  },
  {
    id: 37,
    name: "Pictory",
    categoryLabel: "AI Video",
    epu: "$434.7",
    commission: "20% - 50%",
    traffic: "1.9M /mo",
    recurring: "Lifetime",
    pricing: "$19 - $119",
    country: "United States (US)",
    link: "https://pictory.ai"
  },
  {
    id: 38,
    name: "Vizard",
    categoryLabel: "AI Video",
    epu: "$80.4",
    commission: "25%",
    traffic: "1.8M /mo",
    recurring: "12 months",
    pricing: "$14.5 - $39",
    country: "United States (US)",
    link: "https://vizard.ai"
  },
  {
    id: 39,
    name: "Originality.ai",
    categoryLabel: "AI Detector",
    epu: "$288",
    commission: "25%",
    traffic: "1.8M /mo",
    recurring: "12 months",
    pricing: "$12.95 - $179",
    country: "Canada (CA)",
    link: "https://originality.ai"
  },
  {
    id: 40,
    name: "Imagine AI Art",
    categoryLabel: "AI Design",
    epu: "$585",
    commission: "50%",
    traffic: "1.8M /mo",
    recurring: "Lifetime",
    pricing: "$10 - $120",
    country: "United States (US)",
    link: "https://imagine.art"
  },
  {
    id: 41,
    name: "Captions AI",
    categoryLabel: "AI Ads",
    epu: "$29.99",
    commission: "25%",
    traffic: "1.7M /mo",
    recurring: "3 months",
    pricing: "$9.99 - $69.99",
    country: "United States (US)",
    link: "#"
  },
  {
    id: 42,
    name: "Prepostseo",
    categoryLabel: "AI Writing",
    epu: "$88.56",
    commission: "10% - 30%",
    traffic: "1.6M /mo",
    recurring: "Lifetime",
    pricing: "$4.2 - $45",
    country: "Pakistan (PK)",
    link: "https://prepostseo.com"
  },
  {
    id: 43,
    name: "Zeemo AI",
    categoryLabel: "AI Video",
    epu: "$159.93",
    commission: "25%",
    traffic: "1.6M /mo",
    recurring: "12 months",
    pricing: "$6.67 - $99.95",
    country: "China (CN)",
    link: "https://zeemo.ai"
  },
  {
    id: 44,
    name: "PlayAI",
    categoryLabel: "AI Voice",
    epu: "$310.5",
    commission: "25%",
    traffic: "1.5M /mo",
    recurring: "Lifetime",
    pricing: "$39 - $99",
    country: "United States (US)",
    link: "https://play.ai"
  },
  {
    id: 45,
    name: "Any.do",
    categoryLabel: "AI Assistant",
    epu: "$18",
    commission: "20%",
    traffic: "1.3M /mo",
    recurring: "12 months",
    pricing: "$4.99 - $9.99",
    country: "Israel (IL)",
    link: "https://any.do"
  },
  {
    id: 46,
    name: "Fliki",
    categoryLabel: "AI Video",
    epu: "$294.3",
    commission: "30%",
    traffic: "1.3M /mo",
    recurring: "Lifetime",
    pricing: "$21 - $88",
    country: "United States (US)",
    link: "https://fliki.ai"
  },
  {
    id: 47,
    name: "Rank Math",
    categoryLabel: "AI SEO",
    epu: "$102.57",
    commission: "30%",
    traffic: "1.1M /mo",
    recurring: "2 months",
    pricing: "$83.88 - $599.88",
    country: "India (IN)",
    link: "https://rankmath.com"
  }
];

export default programs;